[package]

name = "rusty-chip8"
version = "0.0.1"
authors = [ "dsipasseuth" ]
edition = "2018"

[dependencies]
async-std = "1.12.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
rand = "0.8.5"
ratatui = "0.28.1"
